---
- name: Converge with config management
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_facts.os_family == 'Debian'

    - name: Wait for systemd to complete initialization.  # noqa command-instead-of-module
      ansible.builtin.command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_facts.service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

  roles:
    - role: lacrif.gitlab_runner
      vars:
        gitlab_runner_manage_config: true
        gitlab_runner_concurrent: 2
        gitlab_runner_check_interval: 3
        gitlab_runner_log_level: "debug"
        gitlab_runner_runners:
          - name: "test-shell-runner"
            url: "https://gitlab.com/"
            token: "test-token-shell"
            executor: "shell"
            description: "Test shell runner for Molecule"
            tag_list: ["shell", "test"]
            run_untagged: true
            locked: false
          - name: "test-docker-runner"
            url: "https://gitlab.com/"
            token: "test-token-docker"
            executor: "docker"
            description: "Test docker runner for Molecule"
            tag_list: ["docker", "test"]
            docker:
              image: "alpine:latest"
              privileged: false
              volumes: ["/cache"]
