---
- name: Verify config management
  hosts: all
  tasks:
    - name: Check gitlab-runner binary is present
      ansible.builtin.command: which gitlab-runner
      register: runner_bin
      changed_when: false

    - name: Assert gitlab-runner binary exists
      ansible.builtin.assert:
        that:
          - runner_bin.rc == 0

    - name: Check gitlab-runner user exists
      ansible.builtin.command: id -u gitlab-runner
      register: runner_user
      changed_when: false

    - name: Assert gitlab-runner user exists
      ansible.builtin.assert:
        that:
          - runner_user.rc == 0

    - name: Check gitlab-runner service is enabled and running
      ansible.builtin.service_facts: {}

    - name: Assert service is running
      ansible.builtin.assert:
        that:
          - "ansible_facts.services['gitlab-runner.service'] is defined and ansible_facts.services['gitlab-runner.service'].state == 'running'"

    - name: Check if config.toml exists
      ansible.builtin.stat:
        path: /etc/gitlab-runner/config.toml
      register: config_file

    - name: Assert config.toml exists with correct permissions
      ansible.builtin.assert:
        that:
          - config_file.stat.exists
          - config_file.stat.mode == '0600'
          - config_file.stat.pw_name == 'root'
          - config_file.stat.gr_name == 'root'

    - name: Read config.toml content
      ansible.builtin.slurp:
        path: /etc/gitlab-runner/config.toml
      register: config_content

    - name: Decode config content
      ansible.builtin.set_fact:
        config_text: "{{ config_content.content | b64decode }}"

    - name: Assert config contains expected values
      ansible.builtin.assert:
        that:
          - "'concurrent = 2' in config_text"
          - "'check_interval = 3' in config_text"
          - "'log_level = \"debug\"' in config_text"
          - "'test-shell-runner' in config_text"
          - "'test-docker-runner' in config_text"
          - "'executor = \"shell\"' in config_text"
          - "'executor = \"docker\"' in config_text"
          - "'image = \"alpine:latest\"' in config_text"

    - name: Verify config.toml is valid TOML
      ansible.builtin.command: gitlab-runner verify
      register: verify_result
      changed_when: false
      failed_when: false

    - name: Display verification result
      ansible.builtin.debug:
        var: verify_result.stdout_lines
